const loadingTexts = [
  'Should be cool, calm, and effortless',
  'Currently scrambling and stumbling',
  'I know you’re in a hurry, but hold on',
  'Doggy-paddling through the sea of knowledge',
  'Let the bullets fly a little longer',
  'Hand-crafting your answer',
  'Rallying the little goblins of Wandering Mountain',
  'Don’t rush me, already writing (new folder created)',
  'Thinking so hard I’m breaking a sweat',
  'CPU about to catch fire',
  'Slow-roasted village coffee — quality takes time',
  'Flipping the knowledge pancake',
  'A toast to myself, almost done',
  'Putting inspiration in the oven',
  'Letting the answer steep a little longer',
  'Maxing out emotional support',
  'Knitting a sweater out of language',
  'Neurons throwing a rave',
  'Insomniac owl deep in thought',
  'Coloring in the answer',
  'Frantically flipping through the knowledge base',
  'Brain circus now in session',
  'Pinching 0s and 1s together',
  'Charging up a big move',
  'Magnifying glass is fogged up — hold on',
  'Trying to understand this wild request',
  'Casting a spell, do not disturb',
  'Waking up my silicon friend',
  'Connecting to the wisdom of cyberspace',
  'Hold on, traveler — running the divination',
  'Crossing the knowledge black hole',
  'Reverse-engineering human intent',
  'Crystal ball is hazy, give it a tap',
  'Code runs faster than a journalist',
  'Operator online, please stand by',
  'Galloping over at full speed',
  'Hauling knowledge at light speed',
  'Last piece of the puzzle',
  'Answer is about to wrap',
  'Launch countdown',
  'Locking onto the target',
];

export function getRandomLoadingText(): string {
  return loadingTexts[Math.floor(Math.random() * loadingTexts.length)];
}
